### PR TITLE
Change access mode of volumes

### PR DESCRIPTION
**Pull request by ywk253100**
Change the access mode of volumes for jobservice, registry and chartmuseum: ReadWriteOnce -> ReadWriteMany

Signed-off-by: Wenkai Yin <yinw@vmware.com>

### CODE REVIEW

**Comment by Timer** [comment]
What was the motivation behind this? Not all storage backends support this mode.

**Comment by ywk253100** [comment]
@Timer The volumes of jobservice, registry and chartmuseum should be read/write by all replicas when deploying with multiple instances.

**Comment by Timer** [comment]
I'm using a single replica right now and omitted this change.

However, this mode is incompatible with anyone deployed on vmware/vSphere: https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/faqs.html#is-readwritemany-volume-supported-with-vsphere-cloud-provider

**Comment by ywk253100** [comment]
@Timer `RWM` works with a single replica even on vSphere but not work with multiple replicas, is this what you mean? If it is, this is the behavior we expect.

**Comment by Timer** [comment]
If `RWM` modify works with a single replica, we should be good then. Thanks!

**Pull request merged**
