### PR TITLE
Add recommended labels

### LINKED ISSUE #1704: Missing recommended labels
For compliance reasons, we would like to have the recommended labels on all the workloads managed by the chart.

https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

### PR DESCRIPTION
**Pull request by xoanmi**
Adding recommended labels based on: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

Close #1704

### CODE REVIEW

**Review by cvegagimenez — APPROVED** [review]

**Comment by Vad1mo** [comment]
This is also related to https://github.com/goharbor/harbor-helm/issues/1471

**Review by Vad1mo — CHANGES_REQUESTED** [review]
Did you try and verify the upgrade backwards compatibility?

**Comment by xoanmi** [comment]
> Did you try and verify the upgrade backwards compatibility?

What do you mean? Try a helm upgrade from lates to this version?

> Did you try and verify the upgrade backwards compatibility?

Good catch! I've removed the new labels from the `matchSelector` as it is immutable. Now the change is backwards compatible 🎉 

**Install latest**
```shell
➜ helm install harbor harbor/harbor \
    --set externalURL=http://core.harbor.domain \
    --set expose.ingress.hosts.core=core.harbor.domain \
    --set persistence.enabled=false
NAME: harbor
LAST DEPLOYED: Wed Feb 14 12:45:49 2024
NAMESPACE: harbor
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Please wait for several minutes for Harbor deployment to complete.
Then you should be able to visit the Harbor portal at http://core.harbor.domain
For more details, please visit https://github.com/goharbor/harbor
```

**Upgrade from release**
```bash
➜ helm upgrade harbor . \
    --set externalURL=http://core.harbor.domain \
    --set expose.ingress.hosts.core=core.harbor.domain \
    --set persistence.enabled=false
Release "harbor" has been upgraded. Happy Helming!
NAME: harbor
LAST DEPLOYED: Wed Feb 14 12:55:45 2024
NAMESPACE: harbor
STATUS: deployed
REVISION: 4
TEST SUITE: None
NOTES:
Please wait for several minutes for Harbor deployment to complete.
Then you should be able to visit the Harbor portal at http://core.harbor.domain
For more details, please visit https://github.com/goharbor/harbor
```

**Comment by xoanmi** [comment]
@Vad1mo could you please review this PR? I think it's a very innocuous change and could be merged without further discussion, isn't it?

**Comment by Vad1mo** [comment]
I am all in here, need to test it thou first to see the backward compatibility.

**Comment by zyyw** [comment]
Do we have a strong reason why we need to add the `Standard labels`, instead of using the current labels. Is there any project that also add the `Standard labels` in addition to the their current ones?

**Review by zyyw — APPROVED** [review]
Thank you for contributing to harbor-helm project!

**Comment by xoanmi** [comment]
> Thank you for contributing to harbor-helm project!

@zyyw could we merge this PR?

**Review by Vad1mo — APPROVED** [review]

**Comment by cvegagimenez** [comment]
Hi @zyyw , 

do you know when this change will be added to a new release?

**Comment by zyyw** [comment]
> Hi @zyyw ,
> 
> do you know when this change will be added to a new release?

If everything goes well, it should be available in the 2nd half of May or early of June.

**Comment by zyyw** [comment]
FYI, if we set `persistence.enabled=true`, the upgrading process will be failed as mentioned in this issue:
* https://github.com/goharbor/harbor-helm/issues/1747

Created a PR to resolve this upgrading issue:
* https://github.com/goharbor/harbor-helm/pull/1749

**Pull request merged**
