### PR TITLE
12182-Postgresql-init-should-change-directory-permissions-in-harbor-db-data-directory

### PR DESCRIPTION
**Pull request by jbrandli**
addresses 12182

### CODE REVIEW

**Comment by ywk253100** [comment]
The issue https://github.com/goharbor/harbor/issues/12182 is reopened in the OSS Harbor repository, let's try to fix it in the entrypoint script so that the solution can apply to both OSS Harbor and Harbor chart

**Comment by ywk253100** [comment]
Dup of https://github.com/goharbor/harbor-helm/pull/493.

**Comment by yydzhou** [comment]
> Dup of #493.

#493  is not resolved at all. It got closed without a validate reason.

**Comment by ywk253100** [comment]
Please refer to https://github.com/goharbor/harbor-helm/issues/444#issuecomment-728789140

**Comment by liubo-it** [comment]
@ywk253100 Can you give me a contact information if you have any questions？

**Pull request closed without merging**
