### PR TITLE
fix external redis existing secret url render

### PR DESCRIPTION
**Pull request by MinerYang**
cherry-pick of : https://github.com/goharbor/harbor-helm/pull/1607
fix: https://github.com/goharbor/harbor/issues/19387

### CODE REVIEW

**Review by ywk253100 — APPROVED** [review]

**Review by zyyw — APPROVED** [review]

**Comment by Kajot-dev** [comment]
@MinerYang  This PR contains a bug, it will not use redis existingSecret for registry component (registry component uses "harbor.redis.password" which still does not use existingSecret

**Comment by MinerYang** [comment]
> @MinerYang This PR contains a bug, it will not use redis existingSecret for registry component (registry component uses "harbor.redis.password" which still does not use existingSecret
registry will use password from registry env
https://github.com/goharbor/harbor-helm/blob/39befead99018ff6f1eb6068074eb094aa871f3f/templates/registry/registry-dpl.yaml#L224

**Comment by Kajot-dev** [comment]
That's **registryctl** container, but not the **registry** container. I deployed version of the chart with this PR and caching in redis enabled and **registry** container was getting NOAUTH from redis, while **registryctl** was not

**Comment by MinerYang** [comment]
> That's **registryctl** container, but not the **registry** container. I deployed version of the chart with this PR and caching in redis enabled and **registry** container was getting NOAUTH from redis, while **registryctl** was not

1. that env is for registry container, registryctl is 

> That's **registryctl** container, but not the **registry** container. I deployed version of the chart with this PR and caching in redis enabled and **registry** container was getting NOAUTH from redis, while **registryctl** was not

Thanks @Kajot-dev! Sorry for the late response and it  indeed another issue introduced by https://github.com/goharbor/harbor-helm/pull/1179

**Pull request merged**
