### PR TITLE
Update Harbor chart to support redis sentinel

### PR DESCRIPTION
**Pull request by ywk253100**
Update Harbor chart to support redis sentinel

Signed-off-by: Wenkai Yin <yinw@vmware.com>

### CODE REVIEW

**Comment by lukasmrtvy** [comment]
Seems that there is a problem with sprig function `ternary` in helm2 build task.

I am not sure what exact version of helm2 is used, but:
> ternary was added in sprig 2.15 

Which is helm >=2.10 https://github.com/helm/helm/blob/release-2.10/glide.yaml#L15

**Comment by lukasmrtvy** [comment]
It would be nice to also support `rediss://` scheme.

**Comment by bitsf** [comment]
> It would be nice to also support `rediss://` scheme.

some extra components in harbor does not support rediss now, so we didn't support this yet

**Comment by lukasmrtvy** [comment]
Is there any PR/Issue ? Something to track.. Thanks

**Comment by ywk253100** [comment]
@lukasmrtvy Thank you for pointing out the helm version issue, we'll update the prerequisites of helm in the doc

**Review by reasonerjt — APPROVED** [review]

**Pull request merged**
