### PR TITLE
Use release name as full name if it contains chart name

### PR DESCRIPTION
**Pull request by ElArtista**
Updated to match all the currently generated helm fullname templates.

### CODE REVIEW

**Comment by ElArtista** [comment]
Fixes double harbor naming like:
```
...
service/harbor-harbor-notary-signer
service/harbor-harbor-database
service/harbor-harbor-trivy
service/harbor-harbor-notary-server
service/harbor-harbor-portal
service/harbor-harbor-core
service/harbor-harbor-jobservice
service/harbor-harbor-redis
service/harbor-harbor-chartmuseum
service/harbor-harbor-registry
...
```

**Comment by reasonerjt** [comment]
@ElArtista 
This PR is a good improvement.
Could you please fix the test failure and update README.md?

Refer to: #821

**Comment by ElArtista** [comment]
I changed the integration test you mentioned but CI still fails

**Comment by ElArtista** [comment]
Updated a reference in some Upgrade.md too.
Seems also that CI checks randomly fail too, the change in the Upgrade.md triggered the CI again that failed this time.

**Comment by ElArtista** [comment]
Rebased to latest master.

**Comment by ElArtista** [comment]
CI Is now clean, this can be merged.

**Review by reasonerjt — APPROVED** [review]

**Review by ywk253100 — APPROVED** [review]

**Pull request merged**
