### PR TITLE
add trivy nodeselector and tolerations

### PR DESCRIPTION
**Pull request by jsaulalonso**

### CODE REVIEW

**Comment by ywk253100** [comment]
@jsaulalonso Could you add the sign-off to pass the DCO checking?

**Comment by jsaulalonso** [comment]
@ywk253100 sure! thanks

**Comment by technologynongmin** [comment]
@jsaulalonso Hi 
When I add trivy nodeselector, execution error 

$helm install harbor  -f values.yaml . --namespace=dev
Error: template: harbor/templates/trivy/trivy-sts.yaml:23:28: executing "harbor/templates/trivy/trivy-sts.yaml" at <include (print $.Template.BasePath "/trivy/trivy-secret.yaml") .>: error calling include: template: harbor/templates/trivy/trivy-secret.yaml:10:15: executing "harbor/templates/trivy/trivy-secret.yaml" at <include "harbor.redisForTrivyAdapter" .>: error calling include: template: harbor/templates/_helpers.tpl:253:10: executing "harbor.redisForTrivyAdapter" at <include "harbor.redis.escapedRawPassword" .>: error calling include: template: harbor/templates/_helpers.tpl:220:10: executing "harbor.redis.escapedRawPassword" at <include "harbor.redis.rawPassword" .>: error calling include: template: harbor/templates/_helpers.tpl:214:55: executing "harbor.redis.rawPassword" at <.Values.redis.external.password>: nil pointer evaluating interface {}.password

**Comment by jsaulalonso** [comment]
@technologynongmin could you show your defined values for trivy and redis blocks, please?

**Comment by technologynongmin** [comment]
> @technologynongmin could you show your defined values for trivy and redis blocks, please?

ok.
trivy 
--trivy:
  enabled: true
  image:
    repository: goharbor/trivy-adapter-photon
    tag: v2.0.1
  serviceAccountName: ""
  replicas: 1
  debugMode: false
  vulnType: "os,library"
  severity: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
  ignoreUnfixed: false
  insecure: false
  gitHubToken: ""
  skipUpdate: false
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi
  podAnnotations: {}
----
redis
redis:
  # if external Redis is used, set "type" to "external"
  # and fill the connection informations in "external" section
  type: internal
  internal:
    # set the service account to be used, default if left empty
    serviceAccountName: ""
    image:
      repository: goharbor/redis-photon
      tag: v2.0.1
    # resources:
    #  requests:
    #    memory: 256Mi
    #    cpu: 100m
    nodeSelector:
      kubernetes.io/hostname: xxxxx
    tolerations: []
    affinity: {}
  podAnnotations: {}

**Review by reasonerjt — APPROVED** [review]

**Pull request merged**
