### PR TITLE
Allow setting of additional labels for services

### PR DESCRIPTION
**Pull request by sebidude**
This PR enables users to set labels on all services.

### CODE REVIEW

**Review by Vad1mo — APPROVED** [review]

**Comment by zyyw** [comment]
@sebidude , thank you for the contribution to harbor-helm! Could you please justify a little bit why you would like to allow setting of additional labels for services?
Thanks again.

**Comment by sebidude** [comment]
It will enable us to automatically configure external loadbalancers where their controller needs certain labels in the services. 
For us, it would have been enough to just set the labels on the `harbor` service, but for filtering in logs and metrics, it can also come handy to have labels on all of them.
Let me know if you need more info on this.

**Comment by zyyw** [comment]
Thanks! @sebidude , could you please update the README.md for this configuration?

**Comment by sebidude** [comment]
Readme is updated. Let me know if you need anything else. 

Thanks

**Comment by sebidude** [comment]
What a pity. Now there are merge conflicts.

**Comment by sebidude** [comment]
Looking at 1.15.0 this pr will never be merged

**Pull request closed without merging**
