### PR TITLE
Add entry for `ingress.className` in README

### PR DESCRIPTION
**Pull request by saip92**
The `ingress.className` value is supported and used by the chart but is missing from the README. This PR adds it to the configuration table.

### CODE REVIEW

**Comment by Vad1mo** [comment]
@saip92, the DCO is missing

**Comment by saip92** [comment]
> @saip92, the DCO is missing

Sorry about that. Fixed it.

**Comment by wy65701436** [comment]
please sync the latest changes to make the ci pass, thanks.

**Review by wy65701436 — APPROVED** [review]
lgtm

**Comment by MinerYang** [comment]
Hi @saip92 ,
Could you help to rebase the branch? Thanks a lot

**Comment by saip92** [comment]
@wy65701436 @MinerYang Apologies! I've been caught up recently and couldn't get to this sooner. Rebased and pushed.

**Review by Vad1mo — APPROVED** [review]

**Pull request merged**
