### PR TITLE
Ability to add custom labels to Ingresses

### PR DESCRIPTION
**Pull request by macno**
When exposing Harbor via ingress it could be needed to set specific labels

### CODE REVIEW

**Comment by mmalyska** [comment]
Fixes: #1142

**Comment by mmalyska** [comment]
@macno Maybe it's worth to update `Readme` too?

**Comment by macno** [comment]
> @macno Maybe it's worth to update `Readme` too?

Absolutely, I'd try to do it ASAP

**Review by zyyw — APPROVED** [review]
LGTM

**Review by ywk253100 — APPROVED** [review]

**Pull request merged**
