### PR TITLE
Add ability to configure an existing secret for S3 type storage

### PR DESCRIPTION
**Pull request by Sea-you**
In the GitOps world, it's a good practice to separate the configuration of secrets from the actual application Helm chart. 

Using secrets provisioned differently (for example with https://external-secrets.io/) makes it much easier to manage the lifecycle of a secret without the headache of "How would I securely inject my secret with Helm during CD?".

Although this PR only aims to fix that for the `persistence.imageChartStorage.s3` use case, it might encourage others to do the same for other `imageChartStorage` cases.

### CODE REVIEW

**Review by zyyw — APPROVED** [review]
lgtm

**Comment by Sea-you** [comment]
PTAL

**Comment by zyyw** [comment]
Hi @Sea-you, thanks for contributing to harbor-helm, could you please squash your commit into one commit message?

**Review by zyyw — APPROVED** [review]

**Review by ywk253100 — APPROVED** [review]

**Comment by frabar** [comment]
Is there any chance to see this feature in the stable version soon?

**Pull request merged**
