### PR TITLE
Update the kubernetes version used in CI

### PR DESCRIPTION
**Pull request by ywk253100**
Update the kubernetes version used in CI

Signed-off-by: Wenkai Yin <yinw@vmware.com>

### CODE REVIEW

**Review by heww — APPROVED** [review]

**Review by reasonerjt — APPROVED** [review]

**Comment by reasonerjt** [comment]
Approved, but I think we should also update the readme.md

**Comment by ywk253100** [comment]
updated

**Comment by Hokwang** [comment]
@reasonerjt Hi, can you tell me why kubernetes 1.18+ needs for harbor 2.2.0+ ?

**Comment by reasonerjt** [comment]
We plan to only support the 3 most recently released versions of k8s.  That said, the chart may work on lower versions, but we will not verify it in the CI.

**Pull request merged**
