### PR TITLE
add className

### PR DESCRIPTION
**Pull request by jetersen**
should allow ingress class resource to work for nginx ingress 👍

### CODE REVIEW

**Comment by jetersen** [comment]
Friendly reminder 😅

**Comment by ninjadq** [comment]
hi @jetersen , could you give more details, why need this `ingressClassName` in spec?

**Comment by jetersen** [comment]
This is required for ingress v1.

As an example see https://kubernetes.github.io/ingress-nginx/#faq-migration-to-apiversion-networkingk8siov1

**Comment by DysphoricUnicorn** [comment]
This would be great if it could be merged. After upgrading ingress-nginx to v1 the ingress controller started returning 404s because I did not have an ingress class set.

If I hadn't just updated most of my other ingresses, this could have been really difficult to debug since the ingress does still look correct

**Comment by jetersen** [comment]
The behavior I saw was that `kubernetes.io/ingress.class` was ignored after upgrading ingress-nginx to v1.
All my sites using our ingress-nginx controller was not responding until `ingressClassName` was added.

**Comment by DysphoricUnicorn** [comment]
That's interesting since my cluster did not have any issues with this at all - when I added the "new" syntax to existing ingresses, I even got the `ingress.networking.k8s.io/whatever unchanged` message

**Comment by jetersen** [comment]
Just noticed the `$ingress.harbor` and `$ingress.notary` perhaps I should move the className to there, so you can use a different one for harbor and notary.

I guess I should also add them to the readme.md

**Comment by jetersen** [comment]
Friendly bump @ninjadq

**Review by ninjadq — APPROVED** [review]
LGTM

**Comment by ninjadq** [comment]
hi @jetersen, sorry for the delayed reply, could you resolve the conflict?

**Comment by jetersen** [comment]
> Just noticed the `$ingress.harbor` and `$ingress.notary` perhaps I should move the className to there, so you can use a different one for harbor and notary.
> 
> I guess I should also add them to the readme.md

@ninjadq  what about this?

Sure, I'll fix conflict.

**Comment by ninjadq** [comment]
> > Just noticed the `$ingress.harbor` and `$ingress.notary` perhaps I should move the className to there, so you can use a different one for harbor and notary.
> > I guess I should also add them to the readme.md
> 
> @ninjadq what about this?
> 
> Sure, I'll fix conflict.

I think we don't move it to `ingress.harbor` and `ingress.notary`. Because currently, we just using one ingress controller for them all

**Comment by jetersen** [comment]
Merge conflict resolved, feel free to squash and merge.

If you want I can also rebase 😅

**Comment by ninjadq** [comment]
> @ninjadq Merge conflict resolved, feel free to squash and merge.
> 
> If you want I can also rebase 😅

hi @jetersen, it's better to rebase it first, could you update this PR?

**Comment by jetersen** [comment]
@ninjadq done

**Comment by jetersen** [comment]
@ninjadq this need another review 😉

**Comment by mcc138** [comment]
Looks good have tested on 1.21.4

**Review by mcc138 — APPROVED** [review]
Habe tested on 1.21.4, looks good to me

**Review by ywk253100 — APPROVED** [review]

**Comment by clement-igonet** [comment]
So finally, how to specify the  IngressClassName to "nginx" ???

**Pull request merged**
