### PR TITLE
Add support to run in the restricted psp enabled k8s

### PR DESCRIPTION
**Pull request by ywk253100**
Add support to run in the restricted psp enabled k8s

Signed-off-by: Wenkai Yin <yinw@vmware.com>

### CODE REVIEW

**Comment by ywk253100** [comment]
Will create another PR to handle the upgrading

**Comment by ywk253100** [comment]
Related issue https://github.com/goharbor/harbor-helm/issues/756

**Review by reasonerjt — APPROVED** [review]

**Review by bitsf — APPROVED** [review]

**Comment by adamcavendish** [comment]
Haven't tested but I think database data are lost after helm upgrade. Hope that we mention the change on the next migration notes.

**Comment by mumrau** [comment]
There was no mention whatsover and I find this quite infuriating: not in this repository, not in the repository, not in the release notes (https://goharbor.io/docs/2.2.0/administration/upgrade/helm-upgrade/).
It is probably going to wreak havoc on many, many installations.

**Pull request merged**
