### PR TITLE
Support external secrets for service tokens and xsrf

### PR DESCRIPTION
**Pull request by darend**
Add support for using external/existing secrets for the following keys:

- registry.secret
- jobservice.secret
- core.secret
- core.xsrfKey

### CODE REVIEW

**Comment by zyyw** [comment]
Thanks for contributing to harbor-helm!
Could you please justify why you would like `external secrets for service tokens and xsrf`?

**Comment by darend** [comment]
> Could you please justify why you would like external secrets for service tokens and xsrf?

This is related to previous requests including https://github.com/goharbor/harbor-helm/issues/189 and https://github.com/goharbor/harbor-helm/pull/1179. A growing practice is to use gitops to automate deployment of charts (ie: [argocd](https://argoproj.github.io/cd/)). Without external secret supports the sensitive values will need to be defined in the values file, or rely on the autogenerated helm values. Exposing in the values file is not secure. Relying on autogenerated values can lead to challenges where every run will produce new values for the secrets. This PR will address this limitation for all of the the remaining sensitive values.

**Comment by darend** [comment]
Hi @zyyw , do you have any concerns with this change?

**Comment by darend** [comment]
@zyyw I have rebased after chart museum was removed

**Review by zyyw — APPROVED** [review]

**Comment by cdemers** [comment]
Hi! Any progress on that PR? As was said before, It would help users of ArgoCD. Especially as ArgoCD provides a valuable information regarding synchronisation status between what's deployed and what's would be deployed based on git. Having the xsrf regenerated every time we render the Helm template to check if there is drift makes it so that it's either always out of sync, or always synchronizing, which is usually not practical.
Thanks!

**Comment by Gigigotrek** [comment]
Hi @zyyw , 

any news about this?

**Review by ywk253100 — APPROVED** [review]

**Comment by zyyw** [comment]
@darend sorry for troubling you. Would you mind rebasing the main branch and resolving the conflicts?

I'll create a separate PR based on this one if we haven't heard from you in one week. But credits go to you.
Thank you for contributing to harbor-helm!

**Comment by darend** [comment]
Hi @zyyw , I will work on rebasing over the next few days

**Comment by zyyw** [comment]
Sounds great!

**Comment by darend** [comment]
[zyyw](https://github.com/zyyw) it has been rebased

**Comment by zyyw** [comment]
Awesome!

**Pull request merged**
