### PR TITLE
Allow setting internalTLS settings for exporter

### LINKED ISSUE #909: internalTLS broken in 1.6.0 due to missing exporter template
The new exporter component for 1.6.0 breaks the use of `internalTLS` because of a reference to a template (`harbor.internalTLS.exporter.secretName`) that does not exist:

https://github.com/goharbor/harbor-helm/blob/v1.6.0/templates/exporter/exporter-dpl.yaml#L74

It looks like some copy/paste was missing?

### PR DESCRIPTION
**Pull request by poblahblahblah**
Fixes #909

### CODE REVIEW

**Comment by poblahblahblah** [comment]
Something to note is that I couldn't figure out if TLS was actually used for the exporter. I suspect it's not, in which case the deployment template should be updated to not look for the key. I can do that if that's desired.

**Comment by heww** [comment]
I think we can't remove the root ca of the internal tls in the exporter because it will access the core API to fetch some info.

**Review by ninjadq — APPROVED** [review]
lgtm

**Comment by ninjadq** [comment]
fixed in this commit https://github.com/goharbor/harbor-helm/pull/949/commits/7c145171e2465df3dc94a46415d7fcd72a916f72

**Pull request closed without merging**
