### PR TITLE
Allow external dependencies in travis

### PR DESCRIPTION
**Pull request by lwj5**
Pull dependencies in requirements.yaml in travis

### CODE REVIEW

**Comment by lwj5** [comment]
@ywk253100 please help to expedite this PR

**Comment by lwj5** [comment]
bump

**Comment by lwj5** [comment]
@ywk253100 @heww could you review this please

**Comment by heww** [comment]
Why do we need this? harbor-helm do not depend on other charts.

**Comment by lwj5** [comment]
As spoken to Steven in slack, it would be beneficial to replace the legacy PostgreSQL and Redis chart to offer more features out of the box. Also, this will allow the project to focus on the core harbor aspect and reduce maintenance of these dependencies, which have generated quite a bit of issues.

https://github.com/goharbor/harbor-helm/pull/551
https://github.com/goharbor/harbor-helm/pull/552

**Comment by heww** [comment]
> As spoken to Steven in slack, it would be beneficial to replace the legacy PostgreSQL and Redis chart for a more widely used chart which offers more features such as high-availability out of the box and well contributed by the community. Also, this will allow the project to focus on the core harbor aspect and reduce maintenance of these dependencies, which have generated quite a bit of open issues.
> 
> I have also done up the PRs for those, which also requires feedback and planning if it were to be put into use
> #551
> #552

OK, I got it.  But it's better to keep the legacy postgres, redis for `harbor-helm` because not everyone need the HA postgres and redis by other charts.

**Comment by ywk253100** [comment]
@lwj5 Thanks for the PR.
As we are leveraging the Github Action to run the CI and it already includes the logic of fetching dependencies, closing this PR.

**Comment by lwj5** [comment]
@ywk253100 No it does not.

```
  go test -v github.com/goharbor/harbor-helm/unittest
  shell: /bin/bash -e {0}
  env:
    GOROOT: /opt/hostedtoolcache/go/1.13.12/x64
=== RUN   TestTrivyStatefulSetTestSuite
=== RUN   TestTrivyStatefulSetTestSuite/TestCustomCA
=== RUN   TestTrivyStatefulSetTestSuite/TestExistingClaim
=== RUN   TestTrivyStatefulSetTestSuite/TestInternalTLSEnabled
=== RUN   TestTrivyStatefulSetTestSuite/TestPersistenceDisabled
=== RUN   TestTrivyStatefulSetTestSuite/TestPersistenceEnabled
--- FAIL: TestTrivyStatefulSetTestSuite (0.22s)
    --- FAIL: TestTrivyStatefulSetTestSuite/TestCustomCA (0.05s)
        template.go:20: 
            	Error Trace:	template.go:20
            	            				trivy_stateful_set_test.go:29
            	            				trivy_stateful_set_test.go:115
            	Error:      	Received unexpected error:
            	            	error while running command: exit status 1; Error: found in Chart.yaml, but missing in charts/ directory: redis
            	Test:       	TestTrivyStatefulSetTestSuite/TestCustomCA
    --- FAIL: TestTrivyStatefulSetTestSuite/TestExistingClaim (0.04s)
        template.go:20: 
            	Error Trace:	template.go:20
            	            				trivy_stateful_set_test.go:29
            	            				trivy_stateful_set_test.go:65
            	Error:      	Received unexpected error:
            	            	error while running command: exit status 1; Error: found in Chart.yaml, but missing in charts/ directory: redis
```

**Comment by lwj5** [comment]
@ywk253100 #637 fixes most of them

Fail to pull dependencies:
- Linting (helm 2)

Working
- Travis
- Integration
- Unit test
- Liniting (helm 3)

**Pull request closed without merging**
