### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by robv8r**
Changed "showed" to "shown".

### CODE REVIEW

**Review by zyyw — APPROVED** [review]
lgtm

**Comment by zyyw** [comment]
@robv8r please refer to this link to add signature to your commit message:
* https://github.com/goharbor/harbor-helm/pull/1355/checks?check_run_id=10118782255

**Review by ywk253100 — APPROVED** [review]

**Comment by zyyw** [comment]
@robv8r Could you please resolve the **DCO** error by adding commit signature? Thanks

**Comment by Vad1mo** [comment]
@robv8r, you are almost there!

**Comment by zyyw** [comment]
closing due to inactivity

**Pull request closed without merging**
