### PR TITLE
Add Prometheus default alerts and Grafana health dashboard

### PR DESCRIPTION
**Pull request by Allex1**
Addresses https://github.com/goharbor/harbor-helm/issues/858

### CODE REVIEW

**Comment by Allex1** [comment]
@zyyw pls review ?

**Comment by zyyw** [comment]
Hi @Allex1,

Thanks for contributing to harbor!
On the one hand, these two manifests introduced by this PR can be created manually and separately even if it's not merged in the harbor-helm project; on the other hand, this feature could enrich the harbor functionalities in terms of monitoring harbor application. Would you be able to continue supporting this feature if there are issues open regarding it?

Currently, we'll keep this PR open and collecting the demand/feedback of this feature from the community.
Thanks again!

**Comment by Allex1** [comment]
> Hi @Allex1,
> 
> Thanks for contributing to harbor! On the one hand, these two manifests introduced by this PR can be created manually and separately even if it's not merged in the harbor-helm project; on the other hand, this feature could enrich the harbor functionalities in terms of monitoring harbor application. Would you be able to continue supporting this feature if there are issues open regarding it?
> 
> Currently, we'll keep this PR open and collecting the demand/feedback of this feature from the community. Thanks again!

@zyyw I agree these can be side-loaded (and that's what we currently do) but these are under feature flag so there are no braking changes. 
Also by having them as part of the harbor-helm project could provide tremendous benefits from the community updates/changes as opposed to manage them internally .
Feedback gathering is fine I guess but that's why I linked to an older issue that was requesting this feature.
Thanks!

**Comment by Allex1** [comment]
@zyyw can we merge this ?

**Comment by Vad1mo** [comment]
@Allex1 as @zyyw correctly mentioned, can you continue to maintain and expand this part in the helm chart?
If so, we can add this functionality to harbor, If not, we should add this to the Wiki as a starting point for users.

**Comment by Allex1** [comment]
@zyyw @Vad1mo I think this should be merged as a starting point for users nevertheless but I can also maintain it.
We had to sub chart this internally and add these resources separately in order to get some monitoring enabled on our stack. Having this ootb should be a good step forward.
Thanks

**Comment by MinerYang** [comment]
We are now not an all-in-one services, and it is introduced the third-party `Prometheus` CRD which we do not have dedicated  resources to maintain it for long term. So we would like to hold this feature.

**Comment by Allex1** [comment]
@MinerYang This is under a feature flag and disabled by default so it's backwards compatible. This is a very common practice in multiple OSS helm charts. In case users want to enable this they will be required to deploy the `PrometheusRule` object themselves. I can add this comment in needed.

**Comment by volker-raschek** [comment]
Hello everyone, as a longtime maintainer of kubernetes environments, I can only endorse X's pull request. 

I agree that this practice is common and would be very happy to see the changes again in a next release of the chart. This would not only reduce complexity for the environment I maintain, but also for anyone who would like to monitor their system without much effort.

**Comment by Allex1** [comment]
closing in favor of https://github.com/goharbor/harbor-helm/pull/1703

**Pull request closed without merging**
