### PR TITLE
Fix #656: Allow S3 multipart upload config

### LINKED ISSUE #656: Allow configuration of registry S3 multipart upload behavior
It is currently not possible to configure the `multipartcopychunksize`, `multipartcopymaxconcurrency`, and `multipartcopythresholdsize` in the registry [config.yml](https://github.com/docker/distribution/blob/master/docs/configuration.md#storage) using the values file of the helm chart.

For some use cases users need to be able to configure this (e.g. to solve https://github.com/goharbor/harbor/issues/12317).

The possibility to configure these values should be added to https://github.com/goharbor/harbor-helm/blob/master/templates/registry/registry-cm.yaml

### PR DESCRIPTION
**Pull request by axelgobletbdr**
Signed-off-by: Axel Goblet <axel.goblet@bigdatarepublic.nl>

### CODE REVIEW

**Comment by axelgobletbdr** [comment]
@ywk253100 when is the planned release for 1.5.0? I would like to know this so I can decide whether to patch this feature in our project, or wait for this PR to be merged.

**Comment by axelgobletbdr** [comment]
@reasonerjt @ywk253100 could you look into this PR?

**Comment by axelgobletbdr** [comment]
@reasonerjt @ywk253100 up

**Comment by axelgobletbdr** [comment]
@heww could you look into this PR? it has been open for over a month now and makes harbor-helm work with Ceph. It is a trivial change adding optional config and does not cause any breaking changes.

**Comment by reasonerjt** [comment]
@axelgobletbdr could you update the document?  Please also mention these attributes will be applied only to the registry, i.e. not chartmuseum?

**Comment by axelgobletbdr** [comment]
Hi @reasonerjt these fields are not mentioned in the [variables](https://github.com/goharbor/harbor-helm/blob/master/README.md#configuration) of the `README.md`. `persistence.imageChartStorage.type` points to the docker registry [docs](https://github.com/docker/distribution/blob/master/docs/configuration.md#storage), where these fields are described. 

Chartmuseum is meant for helm charts. I do not know whether similar problems exist here. I doubt that chunking is necessary there in the first place, as helm charts are usually small in size.

**Review by ywk253100 — APPROVED** [review]

**Review by reasonerjt — APPROVED** [review]

**Pull request merged**
