### PR TITLE
WIP: feat mysql and mariadb

### PR DESCRIPTION
**Pull request by JinXingYoung**
Signed-off-by: yvonnexyang <yvonnexyang@tencent.com>

### CODE REVIEW

**Comment by sylvainOL** [comment]
it shouldn't be merged as long as https://github.com/goharbor/harbor/issues/6534 is not resolved no?

**Comment by JinXingYoung** [comment]
> it shouldn't be merged as long as [goharbor/harbor#6534](https://github.com/goharbor/harbor/issues/6534) is not resolved no?

Yes, adding mysql/mariadb is still being optimized,  I'll mark it as WIP first, and I'll submit Helm changes after harbor PR comes in https://github.com/goharbor/harbor/pull/16615

**Comment by sylvainOL** [comment]
> > it shouldn't be merged as long as [goharbor/harbor#6534](https://github.com/goharbor/harbor/issues/6534) is not resolved no?
> 
> Yes, adding mysql/mariadb is still being optimized, I'll mark it as WIP first, and I'll submit Helm changes after harbor PR comes in [goharbor/harbor#16615](https://github.com/goharbor/harbor/pull/16615)

Hi,
Sorry I didn't saw your PR on harbor main repo for that :)
good!

**Comment by JinXingYoung** [comment]
> > > it shouldn't be merged as long as [goharbor/harbor#6534](https://github.com/goharbor/harbor/issues/6534) is not resolved no?
> > 
> > 
> > Yes, adding mysql/mariadb is still being optimized, I'll mark it as WIP first, and I'll submit Helm changes after harbor PR comes in [goharbor/harbor#16615](https://github.com/goharbor/harbor/pull/16615)
> 
> Hi, Sorry I didn't saw your PR on harbor main repo for that :) good!

That's all right. I should describe more clearly^^

**Pull request closed without merging**
