### PR TITLE
Adds in RBAC, SecurityContext, and PSP groundwork

### PR DESCRIPTION
**Pull request by voor**
This adds in a unique service account for each deployment or statefulset in Harbor, and the accompanying PodSecurityPolicies.

RBAC and PSP are at the moment global, and applied from the values entry, although depending on the permissions for each part they might need to be broken out.

Currently this is failing, since every container is running as root and still tries to `sudo` at startup.

### CODE REVIEW

**Comment by voor** [comment]
This is more or less functioning.  Unfortunately, the underlying containers are doing a lot of file changing ownerships and `sudo` calls that are going to make locking down some of these security contexts a lot more involved.  For now, this at least creates some of the missing pieces to allow installation into a cluster that explicitly removes default PSP.

**Comment by voor** [comment]
Specifically referenced removing the sudo stuff in this issue: https://github.com/goharbor/harbor/issues/8300

**Comment by uLan08** [comment]
Would love to see this merged. If there's anything you need help, let me know!

**Comment by bradkwadsworth** [comment]
This would be wonderful if the ability to add annotations to the ServiceAccount objects were also added. It would make things like enabling IAM Roles for Service Accounts in AWS possible.

**Comment by mkuendig** [comment]
How do we go with this? I would need this too.

**Comment by HugoRh** [comment]
I am also in a case where it would be very convenient to have it!

**Comment by jonkerj** [comment]
Would love to see this merged. What would it take to have someone from Harbor to look at this PR? It has been open for quite a while now

**Comment by jonkerj** [comment]
Hello? Anybody out there?

**Comment by aemaem** [comment]
Does anyone know the status here? This would be very much appreciated!

**Pull request closed without merging**
