### PR TITLE
Add redis/registry/chartmuseum init container to change permission of directory

### PR DESCRIPTION
**Pull request by secret104278**
If permission of redis data volume not correct, redis will not work, and other service depend on redis will fail to start(e.g. jobservice). Furthermore, if jobservice fail to start, web GUI login may fail on higher version of harbor(e.g. v1.10.0).

Although fsGroup is set, but k8s only support certain types of fs to apply the permission. Use init container will make this chart work in most senario.

fixed issues: #480, #379

Signed-off-by: Yu Chih <secret104278@gmail.com>

### CODE REVIEW

**Comment by madianas** [comment]
Cannot use harbor due to this redis permission issue. Please review.

**Comment by Tchoupinax** [comment]
Hello,

What's up with this work ? I have the same issue :(

Thanks

**Comment by secret104278** [comment]
I end up fork repo and patched I by my own. Don't know why there's no one want to review this.

**Comment by Tchoupinax** [comment]
@secret104278 yeah i finally pull the chart, patch the redis's stafulset with your work and publish the chart to my private repository. It works well :) (I needed just the initContainer for redis to solve my issue).

I do not know too.
Thank you for your work ! ^^

**Comment by ywk253100** [comment]
The initContainer solution doesn't work in the restricted psp enabled environment. 
Closing this PR

**Pull request closed without merging**
