### PR TITLE
Ingress requires services to be NodePort not ClusterIP

### PR DESCRIPTION
**Pull request by paulczar**
updates service logic so that if ingress is set the services are exposed
as nodeports where needed.

Signed-off-by: Paul Czarkowski <username.taken@gmail.com>

### CODE REVIEW

**Comment by ywk253100** [comment]
@paulczar Why do we need this PR?

**Comment by paulczar** [comment]
Ahh this may actually be heavy handed.  I'm using Google ingress controller which requires type to be nodeport, I bet a in-cluster ingress might be fine with clusterip.  I'll update this with smarter logic.

**Comment by paulczar** [comment]
GCE ingress is external to the cluster so the services being exposed via ingress need to be NodePort.

Also GCE ingress path rules are very specific, so we need to loosen them with a wildcard.

This leave default behavior as is.

**Comment by paulczar** [comment]
@ywk253100 does my followup comment and commit clear my intentions up for you ?

**Comment by ywk253100** [comment]
@paulczar Please give me more time to investigate the GCE ingress. Thanks.

**Comment by ywk253100** [comment]
@paulczar All your PRs are closed automatically when we fixing #48, you need to re-do the works in the PRs and commit them again, sorry for that.

**Pull request closed without merging**
