### PR TITLE
do not use multiple secrets for ingress when notary is enabled

### PR DESCRIPTION
**Pull request by knackaron**
Enabling Notary is broken due to cert-manager looping between two secrets for the ingress as outlined in https://github.com/goharbor/harbor-helm/issues/365.  This PR corrects that behavior by defining the ingress in the standard way.

broken:
```yaml
$ helm template . -x templates/ingress/ingress.yaml | yq r - spec.tls
- secretName: release-name-harbor-ingress
  hosts:
  - core.harbor.domain
- secretName: release-name-harbor-ingress
  hosts:
  - notary.harbor.domain
```

fixed:
```yaml
$ helm template . -x templates/ingress/ingress.yaml | yq r - spec.tls
- secretName: release-name-harbor-ingress
  hosts:
  - core.harbor.domain
  - notary.harbor.domain
```

### CODE REVIEW

**Comment by Sayrus** [comment]
Hey !

If you intend to remove notarySecretName entirely, you should remove it from the README as well as default values.
You should also ensure that `ingress.host.core` is defined, otherwise you have to create the `hosts` entry in the notary if-block.

**Comment by knackaron** [comment]
Thanks, forgot to check those.  Updated the commit.

Confirmed behavior when hosts might not be set in any scenario:
```bash
$ helm template . -x templates/ingress/ingress.yaml --set expose.ingress.hosts.core= --set expose.ingress.hosts.notary= | yq r - spec.tls
- secretName: release-name-harbor-ingress

$ helm template . -x templates/ingress/ingress.yaml --set expose.ingress.hosts.core= | yq r - spec.tls
- secretName: release-name-harbor-ingress
  hosts:
  - notary.harbor.domain

$ helm template . -x templates/ingress/ingress.yaml --set expose.ingress.hosts.notary= | yq r - spec.tls
- secretName: release-name-harbor-ingress
  hosts:
  - core.harbor.domain
```

**Comment by frvasquezjaquez** [comment]
any plan to fix this?

**Comment by rhysjtevans** [comment]
When will this be merged?

**Pull request closed without merging**
