### PR TITLE
Adding back email and ldap setting

### PR DESCRIPTION
**Pull request by pierredadt**
Hello,

From an operator and system administrator point of view, being able to deploy a product from scratch and 100% automated is a must have.
Choosing to remove the "users" settings from the deployment chart forces an otherwise 100% automated flow to be finished manually.
This choice hence violates the kubernetes paradigm aiming at making applications deployments fully automated and reproducible.

The PR aims at giving the opportunity, if chosen, to be able to deploy Harbor with Email and LDAP connections pre-configured.

What's new: 
- Added back Email settings, and a trigger on the `email.enabled` boolean value to activate of deactivate email configuration
- Added back LDAP settings, and a trigger on the `auth.mode` value to activate of deactivate LDAP configuration
- Added `ingress.labels` value to be able to customize the ingress in case of specific ingress classes
- Completed README.md to reflect above changes and document them

What can be improved:
- The LDAP groups settings are not set, because there is no documentation on the associated env. vars. names and default values. It might be interesting to complete this section

### CODE REVIEW

**Comment by ywk253100** [comment]
@pierredadt Thank you for your PR, but as we discussed in #70, the user settings should be set by API.
We'll not accept this commit. Thanks again.
About the ingress label, can you explain it in more detail?

**Comment by pierredadt** [comment]
@ywk253100 thanks for your input.

I get there is an alternative way to set said settings, and I could stand behind your choice with a more in-depth explanation. I still believe we should at least have the choice between the 2 solutions, especially since there is no real support/documentation on how to operate with API (except the swagger file in harbor repo).

Concerning ingress labels, certain ingress controllers can handle different ingress classes (e.g. http/https, network restricted, ...) and know what to implement depending on labels found in the manifest. 
The labels given are not necessarily the ones used by said controllers, and it is essential to let operators choose the options they need.

That said, do you mind sharing your strategy on users settings handling and the reasons behind it ?

**Comment by ywk253100** [comment]
@pierredadt The reason why the user settings cannot be set by environment variables is explained in #70.

And as I know, different ingress controllers have different annotations to customize their behavior. So what is the label used for? Is there any ingress controller using labels?

**Comment by ywk253100** [comment]
Closing due to inactivity, feel free to reopen it.

**Pull request closed without merging**
