### PR TITLE
Single PVC bound workload capacity can now be statefulSet on demand

### PR DESCRIPTION
**Pull request by mumrau**
Hello,

This PR gives the end-user the possibility to chose whether their workload for jobService, registry, and chartmuseum are `StatefulSets` or `Deployments`.

This is extremely handy and necessary in case we use a `ReadWriteOnce` `PersistentVolume`, indeed, on rolling upgrades, the pvc stays bounded to the pod of the "old replicaset", and thus the pod from the "new replicaset" cannot bind the volume. We need to manually delete the old replicasets for these 3 workloads, which makes it very hard to maintain multiple consistent harbor installations accross clusters.

It solves #260 , https://github.com/goharbor/harbor/issues/8181, and is a different approach than #366 which makes more sense to me. Indeed, if you use RWO volumes, the workload is _stateful_ by nature, and thus deservers the type `StatefulSet`.

I am using this little tweak since harbor 1.7 and have successfully updated all the way to 1.9.1.

### CODE REVIEW

**Comment by tlvenn** [comment]
Hi @ywk253100 , could you please review this PR and merge it if you find it acceptable ? It would be great to include it in the next public 1.2 chart.

Thanks in advance.

**Comment by tlvenn** [comment]
Hi @mumrau,

Thanks for this PR, I think this is the right solution however when a statefulSet is used, we should really be using a volumeClaimTemplate and not create a PVC like we do for a deployment.

Could you update your PR to account for this ? This would be great !

**Comment by ywk253100** [comment]
@tlvenn Sorry for the late reply. We decide to use the fix in PR https://github.com/goharbor/harbor-helm/pull/366. We'll expose the upgrade strategy configuration item.

**Comment by tlvenn** [comment]
No worry, do you have a target date for the 1.3.0 release ?

**Comment by ywk253100** [comment]
It should be on early of Dec if everything goes well

**Comment by mumrau** [comment]
Indeed @tlvenn, it is fixed this way in the chart I use on my clsuters. I forgot to include it in the PR as well obviously.
It seems like this is going to be abandonned anyways.

I still find everything kind of odd, not using `StatefulSet` for something, well, `Stateful`.

**Comment by tlvenn** [comment]
I think it might be interesting to propose it again on top of the merged PR instead of trying to compete with it.

StatefulSet are the way to go for all those scenarios (RWO pvc) imho but it is really hard to upgrade from a declared pvc to a volumeClaimTemplate given you don't control the created pvc name in the later. So when you upgrade an existing harbor installation, the other proposal while not being ideal does solve the problem seamlessly. For new harbor installation, going with StatefulSet is better and should be favored.

**Comment by ywk253100** [comment]
@mumrau Not applications need persistent storage are all `StatefulSet`. When you scale the `StatefulSet`, the pods will use their own persistent volumes, not share a single one among all pods, this is not correct for `jobservice` and `registry`. 
The `jobservice` and `registry` are both `Deployment`  rather than `StatefulSet`.

**Comment by tlvenn** [comment]
Ya that's a good point @ywk253100 and definitely thinking with a replicas > 1 helps understand which is which.

**Comment by ywk253100** [comment]
PR https://github.com/goharbor/harbor-helm/pull/470 is submitted to fix the issue, closing this one

**Pull request closed without merging**
